package sys.modelo;
// Generated 16/09/2023 20:32:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private Set<Matriculacion> matriculacions = new HashSet<Matriculacion>(0);

    public Alumno() {
    }

	
    public Alumno(String nombre, String apellido) {
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Alumno(String nombre, String apellido, Date fechaNacimiento, Set<Matriculacion> matriculacions) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.matriculacions = matriculacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set<Matriculacion> getMatriculacions() {
        return this.matriculacions;
    }
    
    public void setMatriculacions(Set<Matriculacion> matriculacions) {
        this.matriculacions = matriculacions;
    }




}


