package sys.modelo;
// Generated 16/09/2023 20:32:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private Integer id;
     private Profesor profesor;
     private String nombre;
     private Set<Matriculacion> matriculacions = new HashSet<Matriculacion>(0);

    public Asignatura() {
    }

	
    public Asignatura(Profesor profesor, String nombre) {
        this.profesor = profesor;
        this.nombre = nombre;
    }
    public Asignatura(Profesor profesor, String nombre, Set<Matriculacion> matriculacions) {
       this.profesor = profesor;
       this.nombre = nombre;
       this.matriculacions = matriculacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Matriculacion> getMatriculacions() {
        return this.matriculacions;
    }
    
    public void setMatriculacions(Set<Matriculacion> matriculacions) {
        this.matriculacions = matriculacions;
    }




}


