package sys.modelo;
// Generated 16/09/2023 20:32:27 by Hibernate Tools 4.3.1



/**
 * MatriculacionId generated by hbm2java
 */
public class MatriculacionId  implements java.io.Serializable {


     private int idAlumno;
     private int idAsignatura;

    public MatriculacionId() {
    }

    public MatriculacionId(int idAlumno, int idAsignatura) {
       this.idAlumno = idAlumno;
       this.idAsignatura = idAsignatura;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public int getIdAsignatura() {
        return this.idAsignatura;
    }
    
    public void setIdAsignatura(int idAsignatura) {
        this.idAsignatura = idAsignatura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculacionId) ) return false;
		 MatriculacionId castOther = ( MatriculacionId ) other; 
         
		 return (this.getIdAlumno()==castOther.getIdAlumno())
 && (this.getIdAsignatura()==castOther.getIdAsignatura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAlumno();
         result = 37 * result + this.getIdAsignatura();
         return result;
   }   


}


