package sys.modelo;
// Generated 16/09/2023 20:32:27 by Hibernate Tools 4.3.1



/**
 * Matriculacion generated by hbm2java
 */
public class Matriculacion  implements java.io.Serializable {


     private MatriculacionId id;
     private Alumno alumno;
     private Asignatura asignatura;
     private int cantidadAsignaturas;

    public Matriculacion() {
    }

    public Matriculacion(MatriculacionId id, Alumno alumno, Asignatura asignatura, int cantidadAsignaturas) {
       this.id = id;
       this.alumno = alumno;
       this.asignatura = asignatura;
       this.cantidadAsignaturas = cantidadAsignaturas;
    }
   
    public MatriculacionId getId() {
        return this.id;
    }
    
    public void setId(MatriculacionId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public int getCantidadAsignaturas() {
        return this.cantidadAsignaturas;
    }
    
    public void setCantidadAsignaturas(int cantidadAsignaturas) {
        this.cantidadAsignaturas = cantidadAsignaturas;
    }




}


